export const products = 
[
  {
    uri: '/programma-ipoteka-dlya-voennyih-vtb-2688/',
    realtyTypes: [ 'flatNew', 'flatSecondary' ],
    companyId: 7289,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 21,
    minRate: '8.50',
    companySiteUrl: 'https://www.vtb.ru/personal/ipoteka/voennaja-ipoteka/',
    prepayment: 'Полное и частичное',
    totalJobExperience: 0,
    name: 'Ипотека для военных',
    termFrom: 12,
    fines: '',
    insurance: 'Страхование риска утраты или повреждения приобретаемой квартиры обязательно.',
    currency: 'RUR',
    id: 2688,
    companyLogoUrl: 'https://www.cian.ru/image-temp/0/726/494/bank-logo-494627001-6.jpg',
    minAmount: 100000,
    minDeposit: '15.00',
    companyName: 'ВТБ',
    minJobExperience: 0,
    maxAge: 45,
    termTo: 300,
    maxAmount: 2990000,
    realtyRequirements: '',
    requiresSolvencyProof: null,
    contractPlace: 'в отделениях банка'
  },
  {
    uri: '/programma-novostrojki-vtb-2681/',
    realtyTypes: [ 'flatNew' ],
    companyId: 7289,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 0,
    minRate: '7.90',
    companySiteUrl: 'https://www.vtb.ru/personal/ipoteka/novostrojki/#calc_0#',
    prepayment: 'Частичное или полное',
    totalJobExperience: 0,
    name: 'Новостройки',
    termFrom: 12,
    fines: '',
    insurance: 'Комплексное страхование',
    currency: 'RUR',
    id: 2681,
    companyLogoUrl: 'https://www.cian.ru/image-temp/0/726/494/bank-logo-494627001-6.jpg',
    minAmount: 600000,
    minDeposit: '10.00',
    companyName: 'ВТБ',
    minJobExperience: 0,
    maxAge: 0,
    termTo: 360,
    maxAmount: 60000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'в отделениях банка'
  },
  {
    uri: '/programma-pobeda-nad-formalnostyami-vtb-2684/',
    realtyTypes: [ 'flatNew', 'flatSecondary' ],
    companyId: 7289,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 0,
    minRate: '8.90',
    companySiteUrl: 'https://www.vtb.ru/personal/ipoteka/pobeda-nad-formalnostjami/#calc_0#',
    prepayment: 'Полное и частичное',
    totalJobExperience: 0,
    name: 'Победа над формальностями',
    termFrom: 12,
    fines: '',
    insurance: 'Комплексное страхование',
    currency: 'RUR',
    id: 2684,
    companyLogoUrl: 'https://www.cian.ru/image-temp/0/726/494/bank-logo-494627001-6.jpg',
    minAmount: 600000,
    minDeposit: '30.00',
    companyName: 'ВТБ',
    minJobExperience: 0,
    maxAge: 0,
    termTo: 240,
    maxAmount: 30000000,
    realtyRequirements: 'Программа распространяется на покупку вторичного жилья и новостроек.',
    requiresSolvencyProof: null,
    contractPlace: 'в отделениях банка'
  },
  {
    uri: '/programma-bolshe-metrov-nizhe-stavka-vtb-2679/',
    realtyTypes: [ 'flatNew', 'flatSecondary' ],
    companyId: 7289,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 0,
    minRate: '8.10',
    companySiteUrl: 'https://www.vtb.ru/personal/ipoteka/bolshe-metrov/#calc_0#',
    prepayment: 'Частичное или полное',
    totalJobExperience: 0,
    name: 'Больше метров-ниже ставка',
    termFrom: 12,
    fines: '',
    insurance: 'Комплексное страхование',
    currency: 'RUR',
    id: 2679,
    companyLogoUrl: 'https://www.cian.ru/image-temp/0/726/494/bank-logo-494627001-6.jpg',
    minAmount: 600000,
    minDeposit: '20.00',
    companyName: 'ВТБ',
    minJobExperience: 0,
    maxAge: 0,
    termTo: 360,
    maxAmount: 60000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'в отделениях банка'
  },
  {
    uri: '/programma-ipoteka-s-gospodderzhkoj-vtb-12913/',
    realtyTypes: [ 'flatNew', 'flatSecondary' ],
    companyId: 7289,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: null,
    minAge: 0,
    minRate: '5.00',
    companySiteUrl: 'https://www.vtb.ru/personal/ipoteka/dlya-semej-s-detmi/#calc_0#',
    prepayment: '',
    totalJobExperience: 12,
    name: 'Ипотека с господдержкой',
    termFrom: 12,
    fines: '',
    insurance: 'Личное и имущественное страхование',
    currency: 'RUR',
    id: 12913,
    companyLogoUrl: 'https://www.cian.ru/image-temp/0/726/494/bank-logo-494627001-6.jpg',
    minAmount: 500000,
    minDeposit: '20.00',
    companyName: 'ВТБ',
    minJobExperience: 6,
    maxAge: 0,
    termTo: 360,
    maxAmount: 12000000,
    realtyRequirements: 'жилое помещение, реализуемое юридическим лицом (за исключением инвестиционного фонда, в том числе его управляющей компании) по договору:\n' +
      'долевого участия в долевом строительстве (договору уступки прав требования по указанному договору);\n' +
      'купли-продажи (первая продажа).\n' +
      'для Дальневосточного Федерального Округа кредит предоставляется на покупку на вторичном рынке у физ. лица или юр. лица готового жилого помещения или готового жилого помещения с земельным участком, расположенных в сельских поселениях',
    requiresSolvencyProof: true,
    contractPlace: 'Отделения банка'
  },
  {
    uri: '/programma-gospodderzhka-2020-vtb-13102/',
    realtyTypes: [ 'flatNew', 'flatSecondary' ],
    companyId: 7289,
    requiresGoodCreditHistory: true,
    requiresRussiaCitizenship: true,
    pledge: null,
    minAge: 0,
    minRate: '6.50',
    companySiteUrl: 'https://anketa.vtb.ru/ipoteka/?_ga=2.240193738.857083361.1589536655-962754257.1589536655#/step1',
    prepayment: '',
    totalJobExperience: 12,
    name: 'Господдержка 2020',
    termFrom: 12,
    fines: '',
    insurance: '',
    currency: 'RUR',
    id: 13102,
    companyLogoUrl: 'https://www.cian.ru/image-temp/0/726/494/bank-logo-494627001-6.jpg',
    minAmount: 500000,
    minDeposit: '15.00',
    companyName: 'ВТБ',
    minJobExperience: 0,
    maxAge: 0,
    termTo: 240,
    maxAmount: 12000000,
    realtyRequirements: '',
    requiresSolvencyProof: null,
    contractPlace: 'в отделениях банка'
  },
  {
    uri: '/programma-zalogovaya-nedvizhimost-vtb-13072/',
    realtyTypes: [ 'flatNew' ],
    companyId: 7289,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: false,
    pledge: null,
    minAge: 0,
    minRate: '7.80',
    companySiteUrl: 'https://ankety.vtb.ru/mortgage/request/?&_ga=2.122048908.687492292.1577099464-1399667482.1577099464#/0402/51/00/01/01',
    prepayment: 'Частичное или полное погашение можно произвести без посещения отделения через ВТБ-Онлайн',
    totalJobExperience: 0,
    name: 'Залоговая недвижимость',
    termFrom: 12,
    fines: '',
    insurance: '',
    currency: 'RUR',
    id: 13072,
    companyLogoUrl: 'https://www.cian.ru/image-temp/0/726/494/bank-logo-494627001-6.jpg',
    minAmount: 600000,
    minDeposit: '20.00',
    companyName: 'ВТБ',
    minJobExperience: 0,
    maxAge: 0,
    termTo: 360,
    maxAmount: 60000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'в отделениях банка'
  },
  {
    uri: '/programma-vtorichnoe-zhile-vtb-2686/',
    realtyTypes: [ 'flatSecondary' ],
    companyId: 7289,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: false,
    pledge: 'purchasedObject',
    minAge: 0,
    minRate: '7.90',
    companySiteUrl: 'https://anketa.vtb.ru/ipoteka/?_ga=2.226936155.718841992.1575908405-738043932.1575908405#/step1',
    prepayment: 'Полное и частичное',
    totalJobExperience: 0,
    name: 'Вторичное жилье',
    termFrom: 12,
    fines: '',
    insurance: 'Комплексное страхование',
    currency: 'RUR',
    id: 2686,
    companyLogoUrl: 'https://www.cian.ru/image-temp/0/726/494/bank-logo-494627001-6.jpg',
    minAmount: 600000,
    minDeposit: '10.00',
    companyName: 'ВТБ',
    minJobExperience: 0,
    maxAge: 0,
    termTo: 360,
    maxAmount: 60000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'в отделениях банка'
  },
  {
    uri: '/programma-refinansirovanie-vtb-13073/',
    realtyTypes: [ 'flatNew', 'flatSecondary' ],
    companyId: 7289,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: false,
    pledge: null,
    minAge: 0,
    minRate: '8.30',
    companySiteUrl: 'https://anketa.vtb.ru/refinansirovanie-ipoteki/?_ga=2.123090572.687492292.1577099464-1399667482.1577099464#/step1',
    prepayment: 'досрочное погашение без ограничений и штрафов',
    totalJobExperience: 0,
    name: 'Рефинансирование',
    termFrom: 12,
    fines: '',
    insurance: '',
    currency: 'RUR',
    id: 13073,
    companyLogoUrl: 'https://www.cian.ru/image-temp/0/726/494/bank-logo-494627001-6.jpg',
    minAmount: 100000,
    minDeposit: '0.00',
    companyName: 'ВТБ',
    minJobExperience: 0,
    maxAge: 0,
    termTo: 360,
    maxAmount: 30000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'в отделениях банка'
  },
  {
    uri: '/programma-netselevoj-kredit-pod-zalog-nedvizhimosti-vtb-13009/',
    realtyTypes: [
      'flatNew',
      'flatSecondary',
      'houseOrTownhouse',
      'houseBuilding',
      'repair'
    ],
    companyId: 7289,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: null,
    minAge: 0,
    minRate: '10.90',
    companySiteUrl: 'https://www.vtb.ru/personal/ipoteka/ipoteka-pod-zalog-nedvizhimosti/',
    prepayment: 'Досрочное погашение без ограничений и штрафов',
    totalJobExperience: 0,
    name: 'Нецелевой кредит под залог недвижимости',
    termFrom: 12,
    fines: '',
    insurance: '',
    currency: 'RUR',
    id: 13009,
    companyLogoUrl: 'https://www.cian.ru/image-temp/0/726/494/bank-logo-494627001-6.jpg',
    minAmount: 100000,
    minDeposit: '0.00',
    companyName: 'ВТБ',
    minJobExperience: 0,
    maxAge: 0,
    termTo: 240,
    maxAmount: 15000000,
    realtyRequirements: 'Обеспечение по кредиту — залог квартиры в многоквартирном доме, расположенном в черте города присутствия ипотечного подразделения ВТБ, оформляющего кредит.\n' +
      'Закладываемая квартира может находиться в собственности как заемщика, так и супруга / членов семьи, с оформлением поручительства соответствующего лица (лиц)',
    requiresSolvencyProof: true,
    contractPlace: 'в отделениях банков'
  },
  {
    uri: '/programma-novostrojka-sberbank-12799/',
    realtyTypes: [ 'flatNew' ],
    companyId: 7346,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 21,
    minRate: '7.60',
    companySiteUrl: 'https://www.sberbank.ru/ru/person/credits/home/buying_project',
    prepayment: '',
    totalJobExperience: 12,
    name: 'Новостройка',
    termFrom: 12,
    fines: '',
    insurance: 'Обязательное страхование передаваемого в залог имущества (за исключением земельного участка) от рисков утраты/гибели, повреждения в пользу Банка на весь срок действия кредитного договора.',
    currency: 'RUR',
    id: 12799,
    companyLogoUrl: 'https://www.cian.ru/image-temp/1/428/993/bank-logo-399824196-6.jpg',
    minAmount: 300000,
    minDeposit: '15.00',
    companyName: 'Сбербанк',
    minJobExperience: 6,
    maxAge: 75,
    termTo: 360,
    maxAmount: 30000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'В отделениях Банка'
  },
  {
    uri: '/programma-kvartira-v-novostrojke-rajffajzenbank-2670/',
    realtyTypes: [ 'flatNew' ],
    companyId: 7541,
    requiresGoodCreditHistory: true,
    requiresRussiaCitizenship: false,
    pledge: 'purchasedObject',
    minAge: 21,
    minRate: '7.99',
    companySiteUrl: 'https://www.ipoteka.raiffeisen.ru',
    prepayment: 'Полное и частичное',
    totalJobExperience: 12,
    name: 'Квартира в новостройке',
    termFrom: 12,
    fines: '0,06 % от суммы платежа за каждый просроченный день.',
    insurance: 'Имущественное страхование',
    currency: 'RUR',
    id: 2670,
    companyLogoUrl: 'https://www.cian.ru/image-temp/8/979/893/bank-logo-398979885-6.jpg',
    minAmount: 500000,
    minDeposit: '15.00',
    companyName: 'Райффайзенбанк',
    minJobExperience: 6,
    maxAge: 65,
    termTo: 360,
    maxAmount: 26000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'В отделениях Банка'
  },
  {
    uri: '/programma-novostrojki-absolyut-bank-2690/',
    realtyTypes: [ 'flatNew' ],
    companyId: 7447,
    requiresGoodCreditHistory: true,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 21,
    minRate: '8.99',
    companySiteUrl: 'https://absolutbank.ru/personal/loans/mortgage/new-buildings/',
    prepayment: 'Без ограничений',
    totalJobExperience: 12,
    name: 'Новостройки',
    termFrom: 12,
    fines: '0,06% от суммы просроченной задолженности за каждый день просрочки, при этом проценты за пользование кредитом, за соответствующий период нарушения обязательств, не начисляются',
    insurance: 'Договор страхования риска утраты и повреждения Объекта недвижимости, который заключается в обязательном порядке',
    currency: 'RUR',
    id: 2690,
    companyLogoUrl: 'https://www.cian.ru/image-temp/0/100/993/bank-logo-399001075-6.jpg',
    minAmount: 300000,
    minDeposit: '20.01',
    companyName: 'Абсолют Банк',
    minJobExperience: 6,
    maxAge: 65,
    termTo: 360,
    maxAmount: 20000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'в отделениях банка'
  },
  {
    uri: '/programma-novostrojka-bank-sankt-peterburg-12766/',
    realtyTypes: [ 'flatNew' ],
    companyId: 7295,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 18,
    minRate: '9.00',
    companySiteUrl: 'https://www.bspb.ru/retail/mortgage/first/standart/',
    prepayment: 'Досрочное погашение кредита допускается без моратория и штрафных санкций.',
    totalJobExperience: 12,
    name: 'Новостройка',
    termFrom: 12,
    fines: '',
    insurance: 'Комплексное страхование',
    currency: 'RUR',
    id: 12766,
    companyLogoUrl: 'https://www.cian.ru/image-temp/7/900/993/bank-logo-399009768-6.jpg',
    minAmount: 500000,
    minDeposit: '10.00',
    companyName: 'Банк Санкт-Петербург',
    minJobExperience: 4,
    maxAge: 70,
    termTo: 300,
    maxAmount: 30000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'В отделениях Банка'
  },
  {
    uri: '/programma-novostrojka-otkryitie-2637/',
    realtyTypes: [ 'flatNew' ],
    companyId: 7578,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 18,
    minRate: '8.00',
    companySiteUrl: 'https://ipotekaonline.open.ru/registration?from=lp_new_banner&program=new&ref=new&_ga=2.246126468.1073927018.1575918495-1280363316.1575918495',
    prepayment: '',
    totalJobExperience: 12,
    name: 'Новостройка',
    termFrom: 36,
    fines: '',
    insurance: 'Комплексное страхование.',
    currency: 'RUR',
    id: 2637,
    companyLogoUrl: 'https://cdn-p.cian.site/images/8/742/938/bank-logo-839247857-6.jpg',
    minAmount: 500000,
    minDeposit: '20.00',
    companyName: 'Открытие',
    minJobExperience: 3,
    maxAge: 65,
    termTo: 360,
    maxAmount: 30000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'В отделениях Банка'
  },
  {
    uri: '/programma-novostrojka-vozrozhdenie-2702/',
    realtyTypes: [ 'flatNew', 'houseOrTownhouse', 'garage' ],
    companyId: 7478,
    requiresGoodCreditHistory: true,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 18,
    minRate: '8.45',
    companySiteUrl: 'https://www.vbank.ru/mortgage/mortgage_all/novostroyka/form/',
    prepayment: 'Частичное или полное без моратория и комиссии',
    totalJobExperience: 0,
    name: 'Новостройка',
    termFrom: 36,
    fines: 'При нарушении сроков возврата кредита:\n' +
      '-Процентная ставка (проценты годовых), равная ключевой ставке ЦБ РФ, действующей на дату заключения договора от суммы просроченной задолженности по кредиту, если по условиям кредитного договора проценты за соответствующий период нарушения исполнения обязательств начисляются;\n' +
      '-0,06 (ноль целых шесть сотых) процента от суммы просроченной задолженности по кредиту за каждый день нарушения исполнения обязательств, если по условиям кредитного договора, проценты за соответствующий период нарушения исполнения обязательств не начисляются.\n' +
      'При нарушении сроков уплаты начисленных по кредиту процентов:\n' +
      '-Процентная ставка (проценты годовых), равная ключевой ставке ЦБ РФ, действующей на дату заключения договора от суммы просроченной задолженности по уплате процентов, если по условиям кредитного договора проценты за соответствующий период нарушения исполнения обязательств начисляются;\n' +
      '-0,06 (ноль целых шесть сотых) процента от суммы просроченной задолженности по уплате процентов за каждый день нарушения исполнения обязательств, если по условиям кредитного договора, проценты за соответствующий период нарушения исполнения обязательств не начисляются.\n' +
      '-Неустойка в размере 0,2 (ноль целых две десятых) процента от суммы страхового взноса по имущественному страхованию, уплаченного Кредитором за Заемщика, за каждый день просрочки в случае не возмещения Заемщиком понесенных Кредитором расходов (в случае осуществления страхования по индивидуальному договору страхования).',
    insurance: 'Ипотечное страхование',
    currency: 'RUR',
    id: 2702,
    companyLogoUrl: 'https://www.cian.ru/image-temp/7/989/893/bank-logo-398989764-6.jpg',
    minAmount: 300000,
    minDeposit: '10.00',
    companyName: 'Возрождение',
    minJobExperience: 6,
    maxAge: 70,
    termTo: 360,
    maxAmount: 60000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'В отделениях Банка'
  },
  {
    uri: '/programma-novostrojka-investtorgbank-12765/',
    realtyTypes: [ 'flatNew', 'repair', 'houseOrTownhouse' ],
    companyId: 7582,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 20,
    minRate: '9.49',
    companySiteUrl: 'http://www.itb.ru/personal/loans/mortgage/request/?PRODUCT=nedvizhimost',
    prepayment: 'Досрочное погашение на любом этапе сделки без штрафов и комиссий',
    totalJobExperience: 12,
    name: 'Новостройка',
    termFrom: 12,
    fines: '0,02% от суммы просроченной задолженности за каждый календарный день просрочки',
    insurance: 'Комплексное страхование',
    currency: 'RUR',
    id: 12765,
    companyLogoUrl: 'https://www.cian.ru/image-temp/6/346/993/bank-logo-399643659-6.jpg',
    minAmount: 300000,
    minDeposit: '20.00',
    companyName: 'Инвестторгбанк',
    minJobExperience: 3,
    maxAge: 75,
    termTo: 300,
    maxAmount: 15000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'в отделениях банка'
  },
  {
    uri: '/programma-novostrojka-zapsibkombank-12759/',
    realtyTypes: [ 'flatNew' ],
    companyId: 7302,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 20,
    minRate: '7.90',
    companySiteUrl: 'https://www.zapsibkombank.ru/moskva/zayavka-na-kredity/?name=Ипотека%20с%20господдержкой%20под%205%&type=2',
    prepayment: 'Полное и частичное',
    totalJobExperience: 0,
    name: 'Новостройка',
    termFrom: 12,
    fines: '',
    insurance: 'Схема выбирается Заемщиком (Комплексное страхование или Выборочное страхование)',
    currency: 'RUR',
    id: 12759,
    companyLogoUrl: 'https://www.cian.ru/image-temp/3/266/993/bank-logo-399662391-6.jpg',
    minAmount: 50000,
    minDeposit: '10.00',
    companyName: 'Запсибкомбанк',
    minJobExperience: 6,
    maxAge: 75,
    termTo: 360,
    maxAmount: 50000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'В отделениях Банка'
  },
  {
    uri: '/programma-perspektiva-ak-bars-2706/',
    realtyTypes: [ 'flatNew' ],
    companyId: 7294,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 18,
    minRate: '7.99',
    companySiteUrl: 'https://www.akbars.ru/individuals/hypothec/perspektiva/',
    prepayment: 'В любое время без комиссий и ограничений по сумме',
    totalJobExperience: 12,
    name: 'Перспектива',
    termFrom: 12,
    fines: '',
    insurance: 'Имущественное (обязательное) и личное (по желанию)',
    currency: 'RUR',
    id: 2706,
    companyLogoUrl: 'https://cdn-p.cian.site/images/8/588/738/bank-logo-837885837-6.jpg',
    minAmount: 500000,
    minDeposit: '10.00',
    companyName: 'АК Барс',
    minJobExperience: 3,
    maxAge: 70,
    termTo: 300,
    maxAmount: 20000000,
    realtyRequirements: 'При приобретении Объектов недвижимости, находящихся на стадии строительства, компания-застройщик и строящийся объект должны пройти процедуру аккредитации согласно утвержденному Банком порядка, если иное не предусмотрено условиями, программой, схемой кредитования. Решение об аккредитации строящегося объекта действует на срок разрешения на строительство, либо на срок права аренды на земельный участок (в зависимости от того, какой из указанных сроков истекает ранее). В случае если кредитование осуществляется на приобретение Объектов недвижимости, находящихся на стадии строительства, под залог Объектов недвижимости, находящихся в собственности Клиентов и/или третьих лиц, проведение процедуры аккредитации компании-застройщика не является обязательной.',
    requiresSolvencyProof: true,
    contractPlace: 'в отделении банков'
  },
  {
    uri: '/programma-zhilyo-na-pervichnom-ryinke-zenit-2731/',
    realtyTypes: [ 'flatNew', 'houseOrTownhouse' ],
    companyId: 7300,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 22,
    minRate: '9.70',
    companySiteUrl: 'https://ok.zenit.ru/ipoteka/new?programm=3&credit=1000000&period=7',
    prepayment: 'Полное досрочное погашение возможно в любой рабочий день.',
    totalJobExperience: 0,
    name: 'Жильё на первичном рынке',
    termFrom: 12,
    fines: '',
    insurance: 'Обязательное страхование — страхование приобретаемой недвижимости от рисков утраты и повреждения.',
    currency: 'RUR',
    id: 2731,
    companyLogoUrl: 'https://www.cian.ru/image-temp/4/799/893/bank-logo-398997471-6.jpg',
    minAmount: 500000,
    minDeposit: '20.00',
    companyName: 'Зенит',
    minJobExperience: 12,
    maxAge: 65,
    termTo: 360,
    maxAmount: 20000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'в отделениях банка'
  },
  {
    uri: '/programma-kvartira-na-pervichnom-ryinke-moskovskij-kreditnyij-bank-12746/',
    realtyTypes: [ 'flatNew' ],
    companyId: 7417,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 18,
    minRate: '8.25',
    companySiteUrl: 'https://mkb.ru/personal/credits/mortgage',
    prepayment: 'С первого месяца, без штрафов',
    totalJobExperience: 0,
    name: 'Квартира на первичном рынке',
    termFrom: 12,
    fines: '',
    insurance: 'Комплексное ипотечное страхование',
    currency: 'RUR',
    id: 12746,
    companyLogoUrl: 'https://www.cian.ru/image-temp/4/700/993/bank-logo-399007421-6.jpg',
    minAmount: 700000,
    minDeposit: '10.00',
    companyName: 'Московский Кредитный Банк',
    minJobExperience: 0,
    maxAge: 65,
    termTo: 360,
    maxAmount: 30000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'В отделениях Банка'
  },
  {
    uri: '/programma-materinskij-kapital-absolyut-bank-2694/',
    realtyTypes: [ 'flatNew', 'flatSecondary' ],
    companyId: 7447,
    requiresGoodCreditHistory: true,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 21,
    minRate: '9.49',
    companySiteUrl: 'https://absolutbank.ru/personal/loans/mortgage/maternity-capital/',
    prepayment: 'Без ограничений',
    totalJobExperience: 12,
    name: 'Материнский Капитал',
    termFrom: 12,
    fines: '0,06% от суммы просроченной задолженности за каждый день просрочки, при этом проценты за пользование кредитом, за соответствующий период нарушения обязательств, не начисляются',
    insurance: 'Договор страхования риска утраты и повреждения Объекта недвижимости, который заключается в обязательном порядке',
    currency: 'RUR',
    id: 2694,
    companyLogoUrl: 'https://www.cian.ru/image-temp/0/100/993/bank-logo-399001075-6.jpg',
    minAmount: 300000,
    minDeposit: '10.01',
    companyName: 'Абсолют Банк',
    minJobExperience: 6,
    maxAge: 65,
    termTo: 360,
    maxAmount: 20000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'в отделениях банка'
  },
  {
    uri: '/programma-apartamentyi-na-pervichnom-ryinke-bank-sankt-peterburg-12780/',
    realtyTypes: [ 'flatNew' ],
    companyId: 7295,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 18,
    minRate: '9.00',
    companySiteUrl: 'https://www.bspb.ru/retail/mortgage/apartments/first/',
    prepayment: 'Досрочное погашение кредита допускается без моратория и штрафных санкций.',
    totalJobExperience: 12,
    name: 'Апартаменты на первичном рынке',
    termFrom: 12,
    fines: '',
    insurance: 'Комплексное страхование',
    currency: 'RUR',
    id: 12780,
    companyLogoUrl: 'https://www.cian.ru/image-temp/7/900/993/bank-logo-399009768-6.jpg',
    minAmount: 500000,
    minDeposit: '20.00',
    companyName: 'Банк Санкт-Петербург',
    minJobExperience: 4,
    maxAge: 70,
    termTo: 360,
    maxAmount: 20000000,
    realtyRequirements: '',
    requiresSolvencyProof: true,
    contractPlace: 'В отделениях Банка'
  },
  {
    uri: '/programma-apartamentyi-na-pervichnom-ryinke-po-pasportu-bank-sankt-peterburg-12781/',
    realtyTypes: [ 'flatNew' ],
    companyId: 7295,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 18,
    minRate: '9.00',
    companySiteUrl: 'https://www.bspb.ru/retail/mortgage/one-document/',
    prepayment: 'Досрочное погашение кредита допускается без моратория и штрафных санкций.',
    totalJobExperience: 12,
    name: 'Апартаменты на первичном рынке (по паспорту)',
    termFrom: 12,
    fines: '',
    insurance: 'Комплексное страхование',
    currency: 'RUR',
    id: 12781,
    companyLogoUrl: 'https://www.cian.ru/image-temp/7/900/993/bank-logo-399009768-6.jpg',
    minAmount: 500000,
    minDeposit: '30.00',
    companyName: 'Банк Санкт-Петербург',
    minJobExperience: 4,
    maxAge: 70,
    termTo: 360,
    maxAmount: 20000000,
    realtyRequirements: '',
    requiresSolvencyProof: null,
    contractPlace: 'В отделениях Банка'
  },
  {
    uri: '/programma-voennaya-ipoteka-bank-sankt-peterburg-12775/',
    realtyTypes: [ 'flatNew', 'flatSecondary' ],
    companyId: 7295,
    requiresGoodCreditHistory: null,
    requiresRussiaCitizenship: true,
    pledge: 'purchasedObject',
    minAge: 21,
    minRate: '10.00',
    companySiteUrl: 'https://www.bspb.ru/retail/mortgage/military/',
    prepayment: 'Досрочное погашение кредита допускается без моратория и штрафных санкций.',
    totalJobExperience: 12,
    name: 'Военная ипотека',
    termFrom: 12,
    fines: '',
    insurance: 'Страхование риска утраты и повреждения Объекта кредитования на срок, превышающий общий срок кредитования на 1 календарный месяц.',
    currency: 'RUR',
    id: 12775,
    companyLogoUrl: 'https://www.cian.ru/image-temp/7/900/993/bank-logo-399009768-6.jpg',
    minAmount: 500000,
    minDeposit: '15.00',
    companyName: 'Банк Санкт-Петербург',
    minJobExperience: 0,
    maxAge: 45,
    termTo: 240,
    maxAmount: 30000000,
    realtyRequirements: '',
    requiresSolvencyProof: false,
    contractPlace: 'В отделениях Банка'
  }
];

// console.log(products.length);